env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 2017
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-empty:
    - 0
    - allowEmptyCatch:
      - true
  no-console:
    - 0
  no-unused-vars:
    - 0
  no-var:
    - error
  prefer-const:
    - error